enable-magisk-update = false
patches-source = "https://gitlab.com/revanced/revanced-patches"

[Tiktok]
version = "auto"
apkmirror-dlurl = "https://apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly/"
included-patches = "'SIM spoof'"
arch = "both"
